// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeendoWebApp_13f_1cs_20260924.Data;

#nullable disable

namespace TeendoWebApp_13f_1cs_20260924.Migrations
{
    [DbContext(typeof(TeendoDbContext))]
    partial class TeendoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TeendoWebApp_13f_1cs_20260924.Models.Teendo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Hatarido")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Kesz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teendok");
                });
#pragma warning restore 612, 618
        }
    }
}
